# 视频解析工具总开关，修改后重启生效
videotool: true

# 默认解析，即识别最高优先级，修改后重启生效
defaulttool: true

# 缓存删除，非必要不修改！
removeCache: true

# 自定义优先级，「默认解析」关闭后才会生效。修改后重启生效
priority: 800

# 发送合并转发消息，可能多用于抖音解析
sendforwardmsg: true

# 评论图、推送图是否使用深色主题 0为根据时间自动切换 1为浅色 2为深色
Theme: 0

# 渲染精度，可选值50~200，建议100。设置高精度会提高图片的精细度，过高可能会影响渲染与发送速度
renderScale: 100

# 放出API服务（本地部署一个抖音、B站的api服务）
APIServer: false

# API服务端口
APIServerPort: 4567

# API服务日志（是否打印API请求日志）
APIServerLog: false
