import sharp from 'sharp';
import Version from './Version.js';
import { getErrorMessage } from './error-message.js';
import { isRecord } from './record.js';
const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
let watermarkModulePromise = null;
let watermarkLoadWarned = false;
const logWarn = (message) => {
    const hostLogger = globalThis.logger;
    if (typeof hostLogger?.warn === 'function') {
        try {
            hostLogger.warn(message);
            return;
        }
        catch {
            // Fall back to the process logger if the host logger rejects the message.
        }
    }
    console.warn(message);
};
const isPng = (buffer) => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE);
const toImageBuffer = (image) => {
    if (!image)
        return null;
    if (Buffer.isBuffer(image))
        return image;
    if (image instanceof Uint8Array)
        return Buffer.from(image);
    if (typeof image === 'string') {
        const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '');
        return Buffer.from(base64, 'base64');
    }
    return null;
};
const toWatermarkBuffer = (result) => {
    const payload = isRecord(result) ? result.buffer : result;
    return toImageBuffer(payload);
};
/**
 * 取出消息段里的图片字节。分片时要重新编码，所以和水印那条路共用同一套读写，
 * 免得两处各自实现、对适配器返回的段形状理解不一致。
 */
export const readImageBytes = (image) => toImageBuffer(getImagePayload(image));
/** 把新的图片字节写回消息段，保持原段的字段形状（file / data.file / data / base64:// 编码） */
export const replaceImageBytes = (image, payload) => setImagePayload(image, payload);
const getImagePayload = (image) => {
    if (!isRecord(image))
        return image;
    return image.file ??
        (isRecord(image.data) ? image.data.file : undefined) ??
        image.url ??
        (isRecord(image.data) ? image.data.url : undefined) ??
        image.data ??
        image;
};
const encodeImagePayload = (source, payload) => {
    if (typeof source !== 'string')
        return payload;
    if (/^base64:\/\//i.test(source))
        return `base64://${payload.toString('base64')}`;
    if (/^data:image\//i.test(source))
        return `data:image/png;base64,${payload.toString('base64')}`;
    return payload;
};
const setImagePayload = (image, payload) => {
    if (!isRecord(image))
        return segment.image(payload);
    if (Object.prototype.hasOwnProperty.call(image, 'file')) {
        return { ...image, file: encodeImagePayload(image.file, payload) };
    }
    if (isRecord(image.data) && Object.prototype.hasOwnProperty.call(image.data, 'file')) {
        return {
            ...image,
            data: { ...image.data, file: encodeImagePayload(image.data.file, payload) }
        };
    }
    if (Object.prototype.hasOwnProperty.call(image, 'data')) {
        return { ...image, data: encodeImagePayload(image.data, payload) };
    }
    return segment.image(payload);
};
const getWatermarkEncoder = async () => {
    try {
        watermarkModulePromise ||= import('@ikenxuan/watermark');
        const watermark = await watermarkModulePromise;
        return watermark.embedWatermarkToPngBytes;
    }
    catch (error) {
        watermarkModulePromise = null;
        if (!watermarkLoadWarned) {
            watermarkLoadWarned = true;
            logWarn(`[Render] 隐水印模块加载失败，已跳过隐水印: ${getErrorMessage(error)}`);
        }
        return null;
    }
};
export const buildWatermarkText = () => JSON.stringify({
    a: Date.now(),
    b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
    c: `Powered by ${Version.BotName} ${Version.BotVersion}`
});
export const embedWatermark = async (image, watermarkText) => {
    const input = toImageBuffer(image);
    if (!input)
        return null;
    try {
        const embedWatermarkToPngBytes = await getWatermarkEncoder();
        if (!embedWatermarkToPngBytes)
            return null;
        const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer();
        const result = await embedWatermarkToPngBytes(pngBuffer, watermarkText);
        const output = toWatermarkBuffer(result);
        if (!output)
            throw new TypeError('\u9690\u6c34\u5370\u7f16\u7801\u5668\u8fd4\u56de\u4e86\u4e0d\u652f\u6301\u7684\u56fe\u7247\u6570\u636e');
        return output;
    }
    catch (error) {
        logWarn(`[Render] 嵌入隐水印失败: ${getErrorMessage(error)}`);
        return null;
    }
};
export const applyWatermarkToImages = async (images, watermarkText) => {
    if (!Array.isArray(images))
        return images;
    const result = [];
    for (const image of images) {
        const payload = getImagePayload(image);
        const watermarked = payload ? await embedWatermark(payload, watermarkText) : null;
        result.push(watermarked ? setImagePayload(image, watermarked) : image);
    }
    return result;
};
