import sharp from 'sharp';
import Version from './Version.js';
const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
let watermarkModulePromise = null;
let watermarkLoadWarned = false;
const logWarn = (message) => {
    const hostLogger = globalThis.logger;
    if (!hostLogger?.warn?.(message))
        console.warn(message);
};
const isPng = (buffer) => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE);
const toImageBuffer = (image) => {
    if (!image)
        return null;
    if (Buffer.isBuffer(image))
        return image;
    if (image instanceof Uint8Array)
        return Buffer.from(image);
    if (typeof image === 'string') {
        const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '');
        return Buffer.from(base64, 'base64');
    }
    return null;
};
const getImagePayload = (image) => {
    if (!isRecord(image))
        return image;
    return image.file ?? (isRecord(image.data) ? image.data.file : undefined) ?? image.url ?? (isRecord(image.data) ? image.data.url : undefined) ?? image;
};
const setImagePayload = (image, payload) => {
    if (!isRecord(image))
        return segment.image(payload);
    if (Object.prototype.hasOwnProperty.call(image, 'file'))
        return { ...image, file: payload };
    if (isRecord(image.data) && Object.prototype.hasOwnProperty.call(image.data, 'file')) {
        return { ...image, data: { ...image.data, file: payload } };
    }
    return segment.image(payload);
};
const getWatermarkEncoder = async () => {
    try {
        watermarkModulePromise ||= import('@ikenxuan/watermark');
        const watermark = await watermarkModulePromise;
        return watermark.embedWatermarkToPngBytes;
    }
    catch (error) {
        watermarkModulePromise = null;
        if (!watermarkLoadWarned) {
            watermarkLoadWarned = true;
            logWarn(`[Render] 隐水印模块加载失败，已跳过隐水印: ${error instanceof Error ? error.message : String(error)}`);
        }
        return null;
    }
};
export const buildWatermarkText = () => JSON.stringify({
    a: Date.now(),
    b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
    c: `Powered by ${Version.BotName} ${Version.BotVersion}`
});
export const embedWatermark = async (image, watermarkText) => {
    const input = toImageBuffer(image);
    if (!input)
        return null;
    try {
        const embedWatermarkToPngBytes = await getWatermarkEncoder();
        if (!embedWatermarkToPngBytes)
            return null;
        const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer();
        const result = embedWatermarkToPngBytes(pngBuffer, watermarkText);
        return Buffer.isBuffer(result) ? result : Buffer.from(result);
    }
    catch (error) {
        logWarn(`[Render] 嵌入隐水印失败: ${error instanceof Error ? error.message : String(error)}`);
        return null;
    }
};
export const applyWatermarkToImages = async (images, watermarkText) => {
    if (!Array.isArray(images))
        return images;
    const result = [];
    for (const image of images) {
        const payload = getImagePayload(image);
        const watermarked = payload ? await embedWatermark(payload, watermarkText) : null;
        result.push(watermarked ? setImagePayload(image, watermarked) : image);
    }
    return result;
};
function isRecord(value) {
    return typeof value === 'object' && value !== null && !Array.isArray(value);
}
