import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { PluginPath } from '../../dir.js'

export interface BuildMetadata {
  version: string
  buildTime: string
  buildTimestamp: number
  name: string
  description: string
  homepage: string
  commitHash: string
  shortCommitHash: string
}

let cachedMetadata: BuildMetadata | null | undefined

const metadataPath = resolve(PluginPath, 'lib', 'build-metadata.json')

/** Read build metadata generated by the TypeScript build pipeline. */
export const getBuildMetadata = (): BuildMetadata | null => {
  if (cachedMetadata !== undefined) return cachedMetadata

  try {
    if (fs.existsSync(metadataPath)) {
      const value: unknown = JSON.parse(fs.readFileSync(metadataPath, 'utf8'))
      if (isBuildMetadata(value)) {
        cachedMetadata = value
        return value
      }
    }
  } catch {
    // A missing or partially written metadata file must not break error handling.
  }

  cachedMetadata = null
  return null
}

export const formatBuildTime = (isoString: string): string => {
  const date = new Date(isoString)
  if (!Number.isFinite(date.getTime())) return isoString
  const pad = (value: number): string => String(value).padStart(2, '0')
  return `${date.getFullYear()}年${pad(date.getMonth() + 1)}月${pad(date.getDate())}日 ${pad(date.getHours())}:${pad(date.getMinutes())}`
}

/** Generate lib/build-metadata.json after the TypeScript output exists. */
export const generateBuildMetadata = (): BuildMetadata => {
  const packagePath = resolve(PluginPath, 'package.json')
  const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8')) as Record<string, unknown>
  const buildTime = new Date().toISOString()
  const commitHash = readGitValue(['rev-parse', 'HEAD'])
  const shortCommitHash = readGitValue(['rev-parse', '--short', 'HEAD'])
  const metadata: BuildMetadata = {
    version: text(packageJson.version) || '0.0.0',
    buildTime,
    buildTimestamp: Date.now(),
    name: text(packageJson.name) || 'kkkkkk-10086',
    description: text(packageJson.description),
    homepage: text(packageJson.homepage) || 'https://github.com/ikenxuan/kkkkkk-10086',
    commitHash,
    shortCommitHash
  }

  fs.mkdirSync(resolve(PluginPath, 'lib'), { recursive: true })
  fs.writeFileSync(metadataPath, `${JSON.stringify(metadata, null, 2)}\n`, 'utf8')
  cachedMetadata = metadata
  return metadata
}

function readGitValue (args: string[]): string {
  try {
    return execFileSync('git', args, { cwd: PluginPath, encoding: 'utf8' }).trim()
  } catch {
    return 'unknown'
  }
}

function text (value: unknown): string {
  return typeof value === 'string' ? value : ''
}

function isBuildMetadata (value: unknown): value is BuildMetadata {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return typeof record.version === 'string' &&
    typeof record.buildTime === 'string' &&
    typeof record.buildTimestamp === 'number' &&
    typeof record.name === 'string' &&
    typeof record.commitHash === 'string' &&
    typeof record.shortCommitHash === 'string'
}

const entryPath = process.argv[1] ? resolve(process.argv[1]) : ''
if (entryPath && entryPath === fileURLToPath(import.meta.url)) {
  const metadata = generateBuildMetadata()
  console.log(`[build-metadata] ${metadata.shortCommitHash} ${metadata.buildTime}`)
}
