import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'

import {
  assertUnlinkedOwnedPath,
  resolveRequiredRoot
} from './path-safety.ts'

export interface TemplateRegistryEntry {
  file: string
  route: string
}

export interface TemplateRegistryPlan {
  root: string
  templateRoot: string
  generatedRoot: string
  outputFile: string
  entries: readonly TemplateRegistryEntry[]
  source: string
}

export interface TemplateRegistryCheckResult {
  status: 'current' | 'stale'
  outputFile: string
  entryCount: number
}

export interface TemplateRegistrySyncResult {
  outputFile: string
  entryCount: number
}

const assertGeneratedPaths = (plan: TemplateRegistryPlan): void => {
  assertUnlinkedOwnedPath(plan.root, plan.generatedRoot)
  assertUnlinkedOwnedPath(plan.root, plan.outputFile)
}

const toPosixPath = (path: string): string => path.split('\\').join('/')

const walkTemplateEntries = (directory: string): string[] => {
  const files: string[] = []
  const entries = readdirSync(directory, { withFileTypes: true })
    .sort((a, b) => a.name.localeCompare(b.name, 'en'))

  for (const entry of entries) {
    if (
      entry.name.startsWith('.') ||
      entry.name.startsWith('_') ||
      (entry.isDirectory() && entry.name === 'components')
    ) continue

    const absolute = join(directory, entry.name)
    if (entry.isDirectory()) files.push(...walkTemplateEntries(absolute))
    else if (entry.isFile() && entry.name === 'index.tsx') files.push(absolute)
  }

  return files
}

export const discoverTemplateRegistryEntries = (templateRoot: string): TemplateRegistryEntry[] => {
  const absoluteTemplateRoot = resolve(templateRoot)
  return walkTemplateEntries(absoluteTemplateRoot)
    .map(file => ({
      file,
      route: toPosixPath(relative(absoluteTemplateRoot, dirname(file)))
    }))
    .sort((a, b) => a.route.localeCompare(b.route, 'en'))
}

export const createTemplateRegistrySource = (
  entries: readonly TemplateRegistryEntry[],
  generatedRoot: string
): string => {
  if (entries.length === 0) throw new Error('没有找到模板入口')

  const sortedEntries = [...entries].sort((a, b) => a.route.localeCompare(b.route, 'en'))
  const absoluteGeneratedRoot = resolve(generatedRoot)
  const imports = sortedEntries.map((item, index) => {
    const importPath = toPosixPath(relative(absoluteGeneratedRoot, item.file))
    return `import template${index} from ${JSON.stringify(importPath)}`
  })
  const templateEntries = sortedEntries
    .map((item, index) => `  ${JSON.stringify(item.route)}: template${index}`)
    .join(',\n')

  return [
    '// Generated by src/module/tooling/react-template/registry-cli.ts. Do not edit by hand.',
    ...imports,
    '',
    `export const templates = {\n${templateEntries}\n} as const`,
    `export const templateRoutes = ${JSON.stringify(sortedEntries.map(item => item.route), null, 2)} as const`,
    ''
  ].join('\n')
}

export const createTemplateRegistryPlan = (root: string): TemplateRegistryPlan => {
  const absoluteRoot = resolveRequiredRoot(root, '模板注册表根目录')
  const templateRoot = join(absoluteRoot, 'ktr', 'template')
  const generatedRoot = join(absoluteRoot, '.generated')
  const outputFile = join(generatedRoot, 'template-registry.ts')
  const entries = discoverTemplateRegistryEntries(templateRoot)

  if (entries.length === 0) throw new Error(`没有找到模板入口：${templateRoot}`)

  return {
    root: absoluteRoot,
    templateRoot,
    generatedRoot,
    outputFile,
    entries,
    source: createTemplateRegistrySource(entries, generatedRoot)
  }
}

export const checkTemplateRegistry = (root: string): TemplateRegistryCheckResult => {
  const plan = createTemplateRegistryPlan(root)
  assertGeneratedPaths(plan)
  const current = existsSync(plan.outputFile) ? readFileSync(plan.outputFile, 'utf8') : ''

  return {
    status: current === plan.source ? 'current' : 'stale',
    outputFile: plan.outputFile,
    entryCount: plan.entries.length
  }
}

export const syncTemplateRegistry = (root: string): TemplateRegistrySyncResult => {
  const plan = createTemplateRegistryPlan(root)
  assertGeneratedPaths(plan)
  mkdirSync(plan.generatedRoot, { recursive: true })
  assertGeneratedPaths(plan)
  writeFileSync(plan.outputFile, plan.source, 'utf8')

  return {
    outputFile: plan.outputFile,
    entryCount: plan.entries.length
  }
}
