import sharp from 'sharp'
import Version from './Version.js'

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
let watermarkModulePromise: Promise<typeof import('@ikenxuan/watermark')> | null = null
let watermarkLoadWarned = false

type ImagePayload = Buffer | Uint8Array | string
export type ImageMessage = object | ImagePayload

const logWarn = (message: string): void => {
  const hostLogger = globalThis.logger as { warn?: (message: string) => unknown } | undefined
  if (typeof hostLogger?.warn === 'function') {
    try {
      hostLogger.warn(message)
      return
    } catch {
      // Fall back to the process logger if the host logger rejects the message.
    }
  }
  console.warn(message)
}

const isPng = (buffer: Buffer): boolean => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE)

const toImageBuffer = (image: unknown): Buffer | null => {
  if (!image) return null
  if (Buffer.isBuffer(image)) return image
  if (image instanceof Uint8Array) return Buffer.from(image)
  if (typeof image === 'string') {
    const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '')
    return Buffer.from(base64, 'base64')
  }
  return null
}

const toWatermarkBuffer = (result: unknown): Buffer | null => {
  const payload = isRecord(result) ? result.buffer : result
  return toImageBuffer(payload)
}

/**
 * 取出消息段里的图片字节。分片时要重新编码，所以和水印那条路共用同一套读写，
 * 免得两处各自实现、对适配器返回的段形状理解不一致。
 */
export const readImageBytes = (image: ImageMessage): Buffer | null => toImageBuffer(getImagePayload(image))

/** 把新的图片字节写回消息段，保持原段的字段形状（file / data.file / data / base64:// 编码） */
export const replaceImageBytes = (image: ImageMessage, payload: Buffer): ImageMessage => setImagePayload(image, payload)

const getImagePayload = (image: ImageMessage): unknown => {
  if (!isRecord(image)) return image
  return image.file ??
    (isRecord(image.data) ? image.data.file : undefined) ??
    image.url ??
    (isRecord(image.data) ? image.data.url : undefined) ??
    image.data ??
    image
}

const encodeImagePayload = (source: unknown, payload: Buffer): Buffer | string => {
  if (typeof source !== 'string') return payload
  if (/^base64:\/\//i.test(source)) return `base64://${payload.toString('base64')}`
  if (/^data:image\//i.test(source)) return `data:image/png;base64,${payload.toString('base64')}`
  return payload
}

const setImagePayload = (image: ImageMessage, payload: Buffer): ImageMessage => {
  if (!isRecord(image)) return segment.image(payload) as ImageMessage
  if (Object.prototype.hasOwnProperty.call(image, 'file')) {
    return { ...image, file: encodeImagePayload(image.file, payload) }
  }
  if (isRecord(image.data) && Object.prototype.hasOwnProperty.call(image.data, 'file')) {
    return {
      ...image,
      data: { ...image.data, file: encodeImagePayload(image.data.file, payload) }
    }
  }
  if (Object.prototype.hasOwnProperty.call(image, 'data')) {
    return { ...image, data: encodeImagePayload(image.data, payload) }
  }
  return segment.image(payload) as ImageMessage
}

const getWatermarkEncoder = async (): Promise<((imageBytes: Buffer, watermarkText: string) => unknown) | null> => {
  try {
    watermarkModulePromise ||= import('@ikenxuan/watermark')
    const watermark = await watermarkModulePromise
    return watermark.embedWatermarkToPngBytes
  } catch (error: unknown) {
    watermarkModulePromise = null
    if (!watermarkLoadWarned) {
      watermarkLoadWarned = true
      logWarn(`[Render] 隐水印模块加载失败，已跳过隐水印: ${error instanceof Error ? error.message : String(error)}`)
    }
    return null
  }
}

export const buildWatermarkText = (): string => JSON.stringify({
  a: Date.now(),
  b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
  c: `Powered by ${Version.BotName} ${Version.BotVersion}`
})

export const embedWatermark = async (
  image: ImagePayload,
  watermarkText: string
): Promise<Buffer | null> => {
  const input = toImageBuffer(image)
  if (!input) return null
  try {
    const embedWatermarkToPngBytes = await getWatermarkEncoder()
    if (!embedWatermarkToPngBytes) return null
    const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer()
    const result = await embedWatermarkToPngBytes(pngBuffer, watermarkText)
    const output = toWatermarkBuffer(result)
    if (!output) throw new TypeError('\u9690\u6c34\u5370\u7f16\u7801\u5668\u8fd4\u56de\u4e86\u4e0d\u652f\u6301\u7684\u56fe\u7247\u6570\u636e')
    return output
  } catch (error: unknown) {
    logWarn(`[Render] 嵌入隐水印失败: ${error instanceof Error ? error.message : String(error)}`)
    return null
  }
}

export const applyWatermarkToImages = async (
  images: ImageMessage[] | false,
  watermarkText: string
): Promise<ImageMessage[] | false> => {
  if (!Array.isArray(images)) return images
  const result: ImageMessage[] = []
  for (const image of images) {
    const payload = getImagePayload(image)
    const watermarked = payload ? await embedWatermark(payload as ImagePayload, watermarkText) : null
    result.push(watermarked ? setImagePayload(image, watermarked) : image)
  }
  return result
}

function isRecord (value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
