import sharp from 'sharp'
import Version from './Version.js'

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
let watermarkModulePromise: Promise<typeof import('@ikenxuan/watermark')> | null = null
let watermarkLoadWarned = false

type ImagePayload = Buffer | Uint8Array | string
export type ImageMessage = object | ImagePayload

const logWarn = (message: string): void => {
  const hostLogger = globalThis.logger as { warn?: (message: string) => unknown } | undefined
  if (!hostLogger?.warn?.(message)) console.warn(message)
}

const isPng = (buffer: Buffer): boolean => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE)

const toImageBuffer = (image: unknown): Buffer | null => {
  if (!image) return null
  if (Buffer.isBuffer(image)) return image
  if (image instanceof Uint8Array) return Buffer.from(image)
  if (typeof image === 'string') {
    const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '')
    return Buffer.from(base64, 'base64')
  }
  return null
}

const getImagePayload = (image: ImageMessage): unknown => {
  if (!isRecord(image)) return image
  return image.file ?? (isRecord(image.data) ? image.data.file : undefined) ?? image.url ?? (isRecord(image.data) ? image.data.url : undefined) ?? image
}

const setImagePayload = (image: ImageMessage, payload: Buffer): ImageMessage => {
  if (!isRecord(image)) return segment.image(payload) as ImageMessage
  if (Object.prototype.hasOwnProperty.call(image, 'file')) return { ...image, file: payload }
  if (isRecord(image.data) && Object.prototype.hasOwnProperty.call(image.data, 'file')) {
    return { ...image, data: { ...image.data, file: payload } }
  }
  return segment.image(payload) as ImageMessage
}

const getWatermarkEncoder = async (): Promise<((imageBytes: Buffer, watermarkText: string) => unknown) | null> => {
  try {
    watermarkModulePromise ||= import('@ikenxuan/watermark')
    const watermark = await watermarkModulePromise
    return watermark.embedWatermarkToPngBytes
  } catch (error: unknown) {
    watermarkModulePromise = null
    if (!watermarkLoadWarned) {
      watermarkLoadWarned = true
      logWarn(`[Render] 隐水印模块加载失败，已跳过隐水印: ${error instanceof Error ? error.message : String(error)}`)
    }
    return null
  }
}

export const buildWatermarkText = (): string => JSON.stringify({
  a: Date.now(),
  b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
  c: `Powered by ${Version.BotName} ${Version.BotVersion}`
})

export const embedWatermark = async (
  image: ImagePayload,
  watermarkText: string
): Promise<Buffer | null> => {
  const input = toImageBuffer(image)
  if (!input) return null
  try {
    const embedWatermarkToPngBytes = await getWatermarkEncoder()
    if (!embedWatermarkToPngBytes) return null
    const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer()
    const result = embedWatermarkToPngBytes(pngBuffer, watermarkText)
    return Buffer.isBuffer(result) ? result : Buffer.from(result as unknown as Uint8Array)
  } catch (error: unknown) {
    logWarn(`[Render] 嵌入隐水印失败: ${error instanceof Error ? error.message : String(error)}`)
    return null
  }
}

export const applyWatermarkToImages = async (
  images: ImageMessage[] | false,
  watermarkText: string
): Promise<ImageMessage[] | false> => {
  if (!Array.isArray(images)) return images
  const result: ImageMessage[] = []
  for (const image of images) {
    const payload = getImagePayload(image)
    const watermarked = payload ? await embedWatermark(payload as ImagePayload, watermarkText) : null
    result.push(watermarked ? setImagePayload(image, watermarked) : image)
  }
  return result
}

function isRecord (value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}
