import { embedWatermarkToPngBytes } from '@ikenxuan/watermark'
import sharp from 'sharp'
import Version from './Version.js'

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

const isPng = buffer => buffer.length >= 8 && buffer.subarray(0, 8).equals(PNG_SIGNATURE)

const toImageBuffer = image => {
  if (!image) return null
  if (Buffer.isBuffer(image)) return image
  if (image instanceof Uint8Array) return Buffer.from(image)
  if (typeof image === 'string') {
    const base64 = image.replace(/^base64:\/\//, '').replace(/^data:image\/\w+;base64,/, '')
    return Buffer.from(base64, 'base64')
  }
  return null
}

const getImagePayload = image => image?.file ?? image?.data?.file ?? image?.url ?? image?.data?.url ?? image

const setImagePayload = (image, payload) => {
  if (!image || Buffer.isBuffer(image) || typeof image === 'string') return segment.image(payload)
  if (Object.prototype.hasOwnProperty.call(image, 'file')) return { ...image, file: payload }
  if (image.data && Object.prototype.hasOwnProperty.call(image.data, 'file')) return { ...image, data: { ...image.data, file: payload } }
  return segment.image(payload)
}

export const buildWatermarkText = () => JSON.stringify({
  a: Date.now(),
  b: `Generated by ${Version.pluginName} v${Version.version}, with source code open-sourced under the GPL-3.0 license`,
  c: `Powered by ${Version.BotName} ${Version.BotVersion}`
})

/**
 * 将隐水印嵌入图片。输入非 PNG 时先转换为 PNG。
 * @param {Buffer|Uint8Array|string} image 图片数据
 * @param {string} watermarkText 水印文本
 * @returns {Promise<Buffer|null>}
 */
export const embedWatermark = async (image, watermarkText) => {
  const input = toImageBuffer(image)
  if (!input) return null
  try {
    const pngBuffer = isPng(input) ? input : await sharp(input).png().toBuffer()
    const result = embedWatermarkToPngBytes(pngBuffer, watermarkText)
    return Buffer.isBuffer(result) ? result : Buffer.from(result.buffer)
  } catch (error) {
    logger.warn(`[Render] 嵌入隐水印失败: ${error instanceof Error ? error.message : String(error)}`)
    return null
  }
}

/**
 * 对渲染后的图片消息数组应用隐水印。
 * @param {Array<*>|false} images 渲染输出
 * @param {string} watermarkText 水印文本
 * @returns {Promise<Array<*>|false>}
 */
export const applyWatermarkToImages = async (images, watermarkText) => {
  if (!Array.isArray(images)) return images
  const result = []
  for (const image of images) {
    const payload = getImagePayload(image)
    const watermarked = await embedWatermark(payload, watermarkText)
    result.push(watermarked ? setImagePayload(image, watermarked) : image)
  }
  return result
}
