import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync
} from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import {
  checkTemplateRegistry,
  createTemplateRegistrySource,
  discoverTemplateRegistryEntries,
  syncTemplateRegistry
} from '../../src/module/tooling/react-template/registry-generator.js'

const temporaryRoots: string[] = []

const createTemporaryRoot = (): string => {
  const root = mkdtempSync(join(tmpdir(), 'kkkkkk-registry-module-'))
  temporaryRoots.push(root)
  return root
}

const writeTemplateEntry = (root: string, route: string): string => {
  const entry = join(root, 'ktr', 'template', ...route.split('/'), 'index.tsx')
  mkdirSync(dirname(entry), { recursive: true })
  writeFileSync(entry, 'export default {}\n', 'utf8')
  return entry
}

const linkDirectory = (target: string, path: string): void => {
  symlinkSync(target, path, process.platform === 'win32' ? 'junction' : 'dir')
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true })
  }
})

describe('template registry generator module', () => {
  it('generates deterministic route-sorted source without mutating entries', () => {
    const root = createTemporaryRoot()
    const generatedRoot = join(root, '.generated')
    const entries = [
      { route: 'z/card', file: writeTemplateEntry(root, 'z/card') },
      { route: 'a/card', file: writeTemplateEntry(root, 'a/card') }
    ]
    const originalRoutes = entries.map(entry => entry.route)

    const source = createTemplateRegistrySource(entries, generatedRoot)

    expect(source).toBe([
      '// Generated by src/module/tooling/react-template/registry-cli.ts. Do not edit by hand.',
      'import template0 from "../ktr/template/a/card/index.tsx"',
      'import template1 from "../ktr/template/z/card/index.tsx"',
      '',
      'export const templates = {',
      '  "a/card": template0,',
      '  "z/card": template1',
      '} as const',
      'export const templateRoutes = [',
      '  "a/card",',
      '  "z/card"',
      '] as const',
      ''
    ].join('\n'))
    expect(entries.map(entry => entry.route)).toEqual(originalRoutes)
    expect(source).not.toMatch(/tailwind|style\.css/i)
  })

  it('rejects an empty registry instead of generating an unusable bundle entry', () => {
    const root = createTemporaryRoot()

    expect(() => createTemplateRegistrySource([], join(root, '.generated')))
      .toThrow('没有找到模板入口')
  })

  it('discovers only public index.tsx routes at any nesting depth', () => {
    const root = createTemporaryRoot()
    const templateRoot = join(root, 'ktr', 'template')
    writeTemplateEntry(root, 'section/card')
    writeTemplateEntry(root, 'section/card/components/internal')
    writeTemplateEntry(root, 'section/_private/internal')
    writeTemplateEntry(root, 'section/.hidden/internal')
    const ignored = join(templateRoot, 'section', 'ignored', 'view.tsx')
    mkdirSync(dirname(ignored), { recursive: true })
    writeFileSync(ignored, 'export default {}\n', 'utf8')

    const entries = discoverTemplateRegistryEntries(templateRoot)

    expect(entries.map(entry => entry.route)).toEqual(['section/card'])
  })

  it('refuses to write through a linked generated directory', () => {
    const root = createTemporaryRoot()
    const external = createTemporaryRoot()
    writeTemplateEntry(root, 'section/card')
    const outsideRegistry = join(external, 'template-registry.ts')
    writeFileSync(outsideRegistry, 'outside\n', 'utf8')
    const generatedLink = join(root, '.generated')
    linkDirectory(external, generatedLink)

    try {
      expect(() => syncTemplateRegistry(root)).toThrow('符号链接或 Junction')
      expect(readFileSync(outsideRegistry, 'utf8')).toBe('outside\n')
    } finally {
      unlinkSync(generatedLink)
    }
  })

  it('syncs byte-identically and checks stale content without rewriting it', () => {
    const root = createTemporaryRoot()
    writeTemplateEntry(root, 'section/card')

    const first = syncTemplateRegistry(root)
    const firstSource = readFileSync(first.outputFile, 'utf8')
    const second = syncTemplateRegistry(root)

    expect(first.entryCount).toBe(1)
    expect(second).toEqual(first)
    expect(readFileSync(second.outputFile, 'utf8')).toBe(firstSource)
    expect(checkTemplateRegistry(root)).toEqual({
      status: 'current',
      outputFile: first.outputFile,
      entryCount: 1
    })

    writeFileSync(first.outputFile, 'stale\n', 'utf8')
    expect(checkTemplateRegistry(root)).toEqual({
      status: 'stale',
      outputFile: first.outputFile,
      entryCount: 1
    })
    expect(readFileSync(first.outputFile, 'utf8')).toBe('stale\n')
  })

  it('reports a missing generated registry as stale without creating it', () => {
    const root = createTemporaryRoot()
    writeTemplateEntry(root, 'section/card')
    const outputFile = join(root, '.generated', 'template-registry.ts')

    expect(checkTemplateRegistry(root)).toEqual({
      status: 'stale',
      outputFile,
      entryCount: 1
    })
    expect(existsSync(outputFile)).toBe(false)
  })
})
